// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.AspNetCore.Mvc;

namespace Pearogram.Models
{
    public partial class Product
    { 
        public int? productId { get; set; }
        [MaxLength(100, ErrorMessage = "please enter Valid name")]
        [MinLength(5, ErrorMessage = "Please enter Valid name")]
        [Required(ErrorMessage = "Product Name is Required")]
        [Display(Name = "Product Name")]
        [Remote(action:"IsExists" , controller: "Product" , AdditionalFields = "SupplierID", ErrorMessage ="This product has been inserted before with the same supplier")]
        public string productName { get; set; }
        [Range(1, 20, ErrorMessage = "Please enter Valid data \nEnter Quentity Per Unit between (1 ,20)")]
        [Display(Name = "Quentity Per Unit")]
        public double? QuentityPerUnit { get; set; }
        [Display(Name = "Reorder Level")]
        public int? ReorderLevel { get; set; }
        [Required]
        [Display(Name = "Supplier")]
        public int? SupplierID { get; set; }
        [Display(Name = "unit In Stock")]
        public double? unitInStock { get; set; }
        [Display(Name = "Units In Order")]
        public double? UnitsInOrder { get; set; }

        public virtual Supplier Supplier { get; set; }
    }
}