// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Pearogram.Models
{
    public partial class Supplier
    {
        public Supplier()
        {
            Products = new HashSet<Product>();
        }

        public int? SupplierID { get; set; }
        [MaxLength(100, ErrorMessage = "please enter Valid name")]
        [MinLength(5, ErrorMessage = "Please enter Valid name")]
        [Required(ErrorMessage = "Supplier Name is Required")]
        [Display(Name = "Supplier Name")]
        [Remote(action: "UniqueSupplier" , controller: "Supplier", ErrorMessage ="This name is already Existes")]
        public string SupplierName { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}